#!/bin/sh

echo "Try to (re)start dnsmasq DHCP server..."

topdir=$(realpath $(dirname $0)/..)

cmd="dnsmasq --conf-dir=$topdir/etc/dhcp --conf-dir=$topdir/run/dhcp"

pkill -f -- "$cmd"
sleep 1

Run() { LANG=C $cmd --port="$1" 2>&1 | grep -q "Address already in use" && return 1 || return 0; }

Run "53" || { echo "Use DNS port 5353..."; Run "5353"; }

pgrep -f -- "$cmd" | grep -q '' || echo "$0: FAILED"

## EOF ##
