#!/bin/sh

topdir=$(realpath $(dirname $0)/..)
bindir=$topdir/bin
netdir=$topdir/run/net

iface="$1"
action="$2"
f="$netdir/$iface.conf"

Die() { echo "kvm-ifup: ${iface}: Error: $*"; exit 1; }

test -n "$iface" || Die "missing interface name.";
test -f "$f" || Die "missing config: $f"

case "$action" in
"" )	ip link list dev "$iface" 2>/dev/null \
	| grep -q ',UP,' \
	&& Die "interface already active."
	;;
"linkreset" )
	ip link set "$iface" down
	sleep 2
	ip link set "$iface" up
	;;
"ipreset" )
	ip -o addr list dev "$iface" \
	| grep ' inet ' \
	| sed -e 's,.* inet ,,; s, .*,,' \
	| while read a; do ip addr del "$a" dev "$iface"; done
	;;
* ) Die "unknown action $action" ;;
esac

. "$f"
# netmode=proxyarp, ipaddr
# netmode=nat, ...
# netmode=bridge, ...

case "$netmode" in

"proxyarp" )
	#set -x
	for a in $ipaddr; do
		me="$(ip route get "$a"      | grep -- ' src '      | head -1 | sed -e 's,.* src ,,' -e 's, .*,,')"
		test -n "$me" || Die "cannot detect IP for using as router."

		dv="$(ip route get "$a"      | grep -- ' dev '      | head -1 | sed -e 's,.* dev ,,' -e 's, .*,,')"
		test -n "$dv" || Die "cannot detect base interface."

		mm="$(ip addr list dev "$dv" | grep -- " inet $me/" | head -1 | sed -e 's,.*/,,' -e 's, .*,,')"
		test -n "$mm" || Die "cannot detect netmask."

		if arping -I "$dv" -qc3 "$ipaddr"; then
			a="$(ip neighbor show to "$ipaddr" dev "$dv")"
			Die "$ipaddr seems already available on $dv as $a."
		fi

		sysctl "net.ipv4.conf.$iface.proxy_arp=1"  > /dev/null
		sysctl "net.ipv4.conf.$iface.rp_filter=1"  > /dev/null
		sysctl "net.ipv4.conf.$iface.arp_ignore=3" > /dev/null  # ..visibility of IP-aliases on ethX

		ip link set "$iface" up
		ip addr add "$me/$mm" dev "$iface"

		# Remove route automatically added by previous command..
		ip route list proto kernel scope link dev "$iface" \
		| while read dest unused; do
			ip route delete "$dest" dev "$iface"
		done

		ip route add "$a/32" dev "$iface" src "$me"

		logger -s "kvm-ifup: $iface: ip=$a, me=$me/$mm, basedev=$dv."
	done
	$bindir/dnsmasq_restart
	;;

* ) Die "unknown $iface netmode $netmode"; exit 1;;

esac

## EOF ##
