#!/bin/sh

EXT_IFACE="$(ip route get 8.8.8.8 | grep ' dev ' | sed -e 's,.* dev ,,' -e 's, .*,,')"

modprobe vhost-net

# workaround vhost-net bug..
iptables -t mangle -I INPUT -p udp --dport bootpc -j CHECKSUM --checksum-fill
iptables -t mangle -I INPUT -i $EXT_IFACE -j RETURN

sysctl "net.ipv4.ip_forward=1"
sysctl "net.ipv4.conf.$EXT_IFACE.proxy_arp=1"

topdir=$(realpath $(dirname $0)/..)

$topdir/bin/dnsmasq_restart

## EOF ##
