#!/bin/bash

apt-get -y install kvm dnsmasq realpath libconfig-tiny-perl socat arping mercurial htop lsof

# Stop and disable system-wide dnsmasq..
service dnsmasq stop
sed -ie 's,^ENABLED=1,ENABLED=0,' "/etc/default/dnsmasq"
f="/var/run/dnsmasq/dnsmasq.pid"
test -s "$f" && pkill -f "$f" && echo "IMPORTANT!!! Check /etc/resolv.conf after killing system-wide dnsmasq!"

D="/storage/kvm"
mkdir -p "$D"
cd "$D"
mkdir -p bin etc iso presets run/{,dhcp,monitor,net,vnc} vm
#mkdir -p etc/{,dhcp,vm}
hg clone http://code.google.com/p/linuxkvm-loader/ bin
hg clone ssh://repo/vmconf    etc

XEN_RESERVED="00:16:3e"
printf '\nMAC base = %s:%02x:%02x:%02x\n' $XEN_RESERVED \
	$[RANDOM % 128] $[RANDOM % 256] $[RANDOM % 256]

## EOF ##
