#!/bin/bash

#set -x

topdir=$(realpath $(dirname $0)/..)

Die() { echo "$@"; exit 1; }

Assign() {
	#echo "DEBUG: Assign $2: '$1'='$3'"
	test -z "$3" && Die "Error: cannot detect $2."
	eval $1=$3
}

test $# = 1 || Die "Usage: $0 <vmname or vmip>"

case "$1" in
[1-9]*.[1-9]*.[1-9]*.[1-9]* )
	vmip="$1"
	Assign vmdev  "VM netdev"  "$(ip route get $vmip | head -1 | sed -e 's,.* dev ,,' -e 's, .*,,')"
	Assign vmpid  "VM pid"     "$(pgrep -fn ifname=$vmdev)"
	Assign vmmon  "VM monitor" "$(lsof -p $vmpid | grep $topdir/run/monitor | sed -e 's,.* ,,')"
	                    vmsock="$(lsof -p $vmpid | grep $topdir/run/vnc     | sed -e 's,.* ,,')"
	;;
* )
	vmname="$1"
	vmsock="$topdir/run/vnc/$vmname.vnc"
	 vmmon="$topdir/run/monitor/$vmname.mon"
	test -S "$vmmon" || Die "$vmname seems not running, socket $vmmon missing."
	Assign vmpid  "VM pid"     "$(lsof -Fp $vmmon | sed -e 's,p,,')"
	;;
esac

test -S "$vmsock" && vmconsole="UNIX-CONNECT:$vmsock"
vmport="$(netstat -ntlp | grep -w $vmpid/kvm | sed -e 's,.* 127.0.0.1:,,' -e 's, .*,,')"
test -n "$vmport" && vmconsole="TCP:127.0.0.1:$vmport"
test -z "$vmconsole" && Die "Cannot detect TCP/file socket for VNC."

if test -z "$vmport"; then
	vmport=5900
	while netstat -ntlp | awk '{print $4;}' | grep -q ":$vmport"; do : $[vmport++] ; done
fi

Assign pubaddr "Public IP" "$(ip route get 8.8.8.8 | head -1 | sed -e 's,.* src ,,' -e 's, .*,,')"

vncpass=""    #  $[RANDOM % 10] requires Bash, may be missing in plain shell?
for n in 1 2 3 4 5 6 7 8; do vncpass="$vncpass$[RANDOM % 10]"; done
echo change vnc password $vncpass | socat - $vmmon || Die "Error: VM monitor unaccessible!"
echo
echo "VNC password: $vncpass"
echo "VNC address: $pubaddr:$vmport"
# todo!!! sudo -H -u vmconsole (pseudo-user for accessing $topdir/run/vnc)
socat "TCP-LISTEN:$vmport,reuseaddr,bind=$pubaddr" "$vmconsole"
echo "VNC done."

## EOF ##
